services:
  - type: web
    name: hate-speech-api
    env: python
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: "pip install -r requirements-render.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: TF_CPP_MIN_LOG_LEVEL
        value: 2
